noun1 = input("Give me a noun.")
food1 = input("Give me a food.")
bodypart1 = input("Give me a body part.")
adjective1 = input("Give me and adjective.")
place1 = input("Give me a place.")
jobtype1 = input("Give me a job type.")
adjective2 = input("Give me an adjective.")
verb1 = input("Give nme a verb.")
place1 = input("Give me a place.")

print("I went to the " + noun1 + " to get a " + food1 + " It was so delicious")
print("The " + food1 + " I ate made my " + bodypart1 + " " + adjective1 + ".")
print("My " + bodypart1 + " was so" + adjective1 + ". That I had to go to the" + place1 + ". ")
print("The " + jobtype1 + " was so " + adjective2 + " that I had to " + verb1 + " all the way back to " + place1)